services:
  - type: web
    name: resume-grader
    env: python
    plan: free
    region: oregon
    buildCommand: "./download_spacy_model.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.12
